name: Expose Pythons
description: Exposes Pythons on the PATH.
runs:
  using: composite
  steps:
    - name: Expose Pythons
      run: |
        if [[ "$(uname -s)" == "Darwin" ]]; then
          toolcache="/Users/runner/hostedtoolcache"
        else
          toolcache="/opt/hostedtoolcache"
        fi

        echo "::group::Exposing Pythons"
        for python_bin_dir in ${toolcache}/Python/*/x64/bin; do
          # N.B.: Python 2.7 prints the version to stderr so we re-direct to get output all on one
          # line in that case.
          echo "Exposing ${python_bin_dir}: $(${python_bin_dir}/python --version 2>&1)"
          PATH="${PATH}:${python_bin_dir}"
        done
        echo "::endgroup::"

        echo "PATH=${PATH}" >> $GITHUB_ENV
      shell: bash
